Synchronize Gradle projects with workspace failed due to an error connecting to the Gradle build. The supplied build action failed with an exception.
Could not resolve all dependencies for configuration
':so-web:detachedConfiguration6'.
Could not find com.withwiz:plankton:0.1.3.
Searched in the following locations:
    https://repo1.maven.org/maven2/com/withwiz/plankton/0.1.3/plankton-0.1.3.pom
    https://repo1.maven.org/maven2/com/withwiz/plankton/0.1.3/plankton-0.1.3.jar
Required by:
    project :so-web > project :so-serviceprocessor
org.gradle.tooling.BuildActionFailureException: The supplied build
action failed with an exception.

pull 한 후에 최초 그래들 빌드시 에러 발생 repositories 에 jcenter() 추가